### ISSUE TITLE
Dark mode flashes

### ISSUE THREAD

**Issue by ddbruce** [rpiambulance/headsup#54]
Dark mode seems to flash semi-regularly into light mode and back. I haven't dug into the code yet.

**Comment by alexmattoni** [comment]
I messed around with it and it looks like since the `updateDate()` method in `whiteboard.js` sets the media attribute on every call the page will sometimes flash when doing so.

If you change the interval at which `updateDate()` is called from 2000 to a low number from 1-10 it will go nuts, although I don't know why it happens on only some calls (because otherwise the issue would happen every 2000ms, no?).

I fixed it on my fork with a global variable to keep track of whether it is night, allowing for a check to ensure the change only happens twice a day (day->night & night->day), although I don't know if that would be a preferred solution.

**Comment by ddbruce** [comment]
Yeah, either that or checking which stylesheet is being used and only changing if it's appropriate to do so based on time.

**Comment by ddbruce** [comment]
Fixed by #59
